version: '3.9'

services:
  pgdb:
    container_name: beer_pong_from_live
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./latest.dump:/docker-entrypoint-initdb.d/latest.dump
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'
